services:
  model:
    build: ./Model
    container_name: glycosnap_flask
    volumes:
      - ./Model:/app
      - ./Model/credentials:/app/credentials:ro
      - C:/GlycoSnap/model:/tmp
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/credentials.json
      - FLASK_APP=app.py
      - DOCKER_ENV=true
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]

  flutter_app:
    build: 
      context: .
    container_name: glycosnap_flutter
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - model
    environment:
      - FLASK_API_URL=http://model:5000
    command: ["flutter", "run", "--debug", "--web-port", "8080"]