
# Use latest Flutter SDK image
FROM ghcr.io/cirruslabs/flutter:3.29.1  

# Set working directory
WORKDIR /app  

# Install CMake for Linux development  
RUN apt-get update && apt-get install -y cmake  

# Copy dependency files and install dependencies
COPY pubspec.yaml pubspec.lock ./  
RUN flutter pub get  

# Copy the rest of the project files
COPY . .  

# Run the app in development mode
CMD ["flutter", "run", "--debug"]
