// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz5L4MzTyxpaW5grPJrLJ8hfKobPjwrq0',
    appId: '1:99321403066:web:feb1cfe8672a5a8683d483',
    messagingSenderId: '99321403066',
    projectId: 'glycosnap-67b4f',
    authDomain: 'glycosnap-67b4f.firebaseapp.com',
    storageBucket: 'glycosnap-67b4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUsx97k6bniHbujcdV3o_z-vSu9hMAjQ0',
    appId: '1:99321403066:android:b4713161a91d013a83d483',
    messagingSenderId: '99321403066',
    projectId: 'glycosnap-67b4f',
    storageBucket: 'glycosnap-67b4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcTwXhHQPrTQgsQjRIt82JaJT0ywta7V8',
    appId: '1:99321403066:ios:b0b65e7190ebfe2483d483',
    messagingSenderId: '99321403066',
    projectId: 'glycosnap-67b4f',
    storageBucket: 'glycosnap-67b4f.appspot.com',
    iosBundleId: 'com.example.glycosnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcTwXhHQPrTQgsQjRIt82JaJT0ywta7V8',
    appId: '1:99321403066:ios:b0b65e7190ebfe2483d483',
    messagingSenderId: '99321403066',
    projectId: 'glycosnap-67b4f',
    storageBucket: 'glycosnap-67b4f.appspot.com',
    iosBundleId: 'com.example.glycosnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz5L4MzTyxpaW5grPJrLJ8hfKobPjwrq0',
    appId: '1:99321403066:web:93cc86e086d4bb7283d483',
    messagingSenderId: '99321403066',
    projectId: 'glycosnap-67b4f',
    authDomain: 'glycosnap-67b4f.firebaseapp.com',
    storageBucket: 'glycosnap-67b4f.appspot.com',
  );
}
